default_stages: [commit, push]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: end-of-file-fixer
        exclude: 'backend/docs/'
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: test
        language: script
        name: Run Tests
        entry: ./scripts/test.sh
  - repo: local
    hooks:
      - id: format
        language: script
        name: Run Format
        entry: ./scripts/format.sh
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.13.0
    hooks:
      - id: commitizen
        stages: [commit-msg]
