version: '3'

tasks:
  build:
    - |
      cd client
      npm install
      cd ../backend
      go mod tidy
      go install .

  format:
    - |
      cd client
      npm run format
      cd ../backend
      go fmt
      go vet
      golangci-lint run ./...

  start-backend:
    - |
      cd backend
      swag i --parseDependency
      go run main.go

  start-frontend:
    - |
      cd client
      npm start

  start-ngrok:
    - |
      cd backend
      echo "Type ngrok domain name:"
      read ngrok;
      ngrok http --domain=${ngrok} 8080

  start-docker:
    - |
      docker-compose down
      docker-compose up

  test-all:
    - |
      cd backend
      go test -count=1 carewallet/...

  pre-commit:
    - pre-commit run --all-files
