version: '3'

tasks:
  build:
    - |
      npm install --prefix client
      go mod tidy

  start-backend:
    - |
      cd backend
      swag i --parseDependency
      go run main.go

  start-frontend:
    - |
      cd client
      npm start

  start-ngrok:
    - |
      cd backend
      echo "Type ngrok domain name:"
      read ngrok;
      ngrok http --domain=${ngrok} 8080

  start-docker:
    - |
      docker-compose down
      docker-compose up

  test-all:
    - |
      cd backend
      go test -count=1 carewallet/...

  pre-commit:
    - pre-commit run --all-files
