version: '3'

tasks:
  build:
    - |
      npm install --prefix client
      go get .
      go mod tidy

  start-backend:
    - |
      swag i --parseDependency
      go run main.go

  start-frontend:
    - npm start --prefix client

  start-ngrok:
    - |
      echo "Type ngrok domain name:"
      read ngrok;
      ngrok http --domain=${ngrok} 8080

  start-docker:
    - |
      docker-compose down
      docker-compose up

  test-all:
    - |
      go test -count=1 carewallet/backend/...

  pre-commit:
    - pre-commit run --all-files
