basePath: /
definitions:
  models.CareGroup:
    properties:
      date_created:
        type: string
      group_id:
        type: integer
      group_name:
        type: string
    type: object
  models.File:
    properties:
      file_id:
        type: integer
      file_name:
        type: string
      file_size:
        type: integer
      group_id:
        type: integer
      task_id:
        type: integer
      upload_by:
        type: string
      upload_date:
        type: string
    type: object
  models.GroupRole:
    properties:
      group_id:
        type: integer
      role:
        $ref: '#/definitions/models.Role'
      user_id:
        type: string
    type: object
  models.Medication:
    properties:
      medication_id:
        type: integer
      medication_name:
        type: string
    type: object
  models.Role:
    enum:
    - PATIENT
    - PRIMARY
    - SECONDARY
    type: string
    x-enum-varnames:
    - RolePatient
    - RolePrimary
    - RoleSecondary
info:
  contact: {}
  description: This is an API for the Care-Wallet App.
  title: Care-Wallet API
  version: "1.0"
paths:
  /files/upload:
    post:
      description: Upload a file to database and S3 bucket
      parameters:
      - description: Body with file zip
        in: formData
        name: file_data
        required: true
        type: file
      - description: The userId of the uploader
        in: formData
        name: upload_by
        required: true
        type: string
      - description: The groupId of the uploader
        in: formData
        name: group_id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.File'
        "400":
          description: Bad Request
          schema:
            type: string
      summary: Upload a file
      tags:
      - file
  /group/{groupId}:
    get:
      description: retrieve all users in given group id
      parameters:
      - description: group id
        in: path
        name: groupId
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
        "400":
          description: Bad Request
          schema:
            type: string
      summary: Get all members from a group
      tags:
      - group
  /group/add/{userId}/{groupId}/{role}:
    post:
      description: Adds a user to a care group given a userID, groupID, and role
      parameters:
      - description: user id
        in: path
        name: userId
        required: true
        type: string
      - description: group id
        in: path
        name: groupId
        required: true
        type: string
      - description: role
        in: path
        name: role
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.CareGroup'
            type: array
        "400":
          description: Bad Request
          schema:
            type: string
      summary: Adds a user to a care group
      tags:
      - group
  /group/create/{groupName}:
    post:
      description: Creates a new care group with the provided group name.
      parameters:
      - description: group name
        in: path
        name: groupName
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.CareGroup'
            type: array
      summary: Creates a care group
      tags:
      - group
  /group/member/{uid}:
    get:
      description: get the group id from the user id
      parameters:
      - description: user id
        in: path
        name: uid
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
      summary: Retrieve a group id given a user id
      tags:
      - group
  /group/roles:
    get:
      description: get all group roles from the db
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.GroupRole'
            type: array
      summary: Get all group roles
      tags:
      - group
  /medications:
    get:
      description: get all user medications
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Medication'
            type: array
      summary: Get All Meds
      tags:
      - medications
    post:
      description: add a medication to a users medlist
      parameters:
      - description: a medication
        in: body
        name: _
        required: true
        schema:
          $ref: '#/definitions/models.Medication'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Medication'
        "400":
          description: Bad Request
          schema:
            type: string
      summary: add a medication
      tags:
      - medications
swagger: "2.0"
