basePath: /
definitions:
  models.Medication:
    properties:
      medication_id:
        type: integer
      medication_name:
        type: string
    type: object
  models.TaskUser:
    properties:
      taskID:
        type: integer
      userID:
        type: string
    type: object
info:
  contact: {}
  description: This is an API for the Care-Wallet App.
  title: Care-Wallet API
  version: '1.0'
paths:
  /files/upload:
    post:
      description: Upload a file to database and S3 bucket
      responses:
        '200':
          description: OK
      summary: Upload a file
      tags:
        - file
  /medications:
    get:
      description: get all user medications
      responses:
        '200':
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Medication'
            type: array
      summary: Get All Meds
      tags:
        - medications
  /tasks/{tid}/assignees:
    post:
      description: assign users to task
      responses:
        '200':
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.TaskUser'
            type: array
      summary: Assign Users To Task
      tags:
        - tasks
  /tasks/{tid}/remove:
    delete:
      description: remove users from task
      responses:
        '200':
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.TaskUser'
            type: array
      summary: Remove Users From Task
      tags:
        - tasks
swagger: '2.0'
